# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plan5.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 160)
        Form.setStyleSheet("*{\n"
"    font-size: 12pt;\n"
"    font-family: sans-serif;\n"
"    background-color: #2a323b;\n"
"    color: #ff9900;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #20252b;\n"
"}")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 201, 20))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 61, 21))
        self.label.setObjectName("label")
        self.hours = QtWidgets.QComboBox(Form)
        self.hours.setGeometry(QtCore.QRect(130, 50, 61, 19))
        self.hours.setObjectName("hours")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.minutes = QtWidgets.QComboBox(Form)
        self.minutes.setGeometry(QtCore.QRect(130, 90, 61, 19))
        self.minutes.setObjectName("minutes")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.minutes.addItem("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 61, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 130, 111, 21))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Добавление будильника"))
        self.label.setText(_translate("Form", "Часы:"))
        self.hours.setItemText(0, _translate("Form", "0"))
        self.hours.setItemText(1, _translate("Form", "1"))
        self.hours.setItemText(2, _translate("Form", "2"))
        self.hours.setItemText(3, _translate("Form", "3"))
        self.hours.setItemText(4, _translate("Form", "4"))
        self.hours.setItemText(5, _translate("Form", "5"))
        self.hours.setItemText(6, _translate("Form", "6"))
        self.hours.setItemText(7, _translate("Form", "7"))
        self.hours.setItemText(8, _translate("Form", "8"))
        self.hours.setItemText(9, _translate("Form", "9"))
        self.hours.setItemText(10, _translate("Form", "10"))
        self.hours.setItemText(11, _translate("Form", "11"))
        self.hours.setItemText(12, _translate("Form", "12"))
        self.hours.setItemText(13, _translate("Form", "13"))
        self.hours.setItemText(14, _translate("Form", "14"))
        self.hours.setItemText(15, _translate("Form", "15"))
        self.hours.setItemText(16, _translate("Form", "16"))
        self.hours.setItemText(17, _translate("Form", "17"))
        self.hours.setItemText(18, _translate("Form", "18"))
        self.hours.setItemText(19, _translate("Form", "19"))
        self.hours.setItemText(20, _translate("Form", "20"))
        self.hours.setItemText(21, _translate("Form", "21"))
        self.hours.setItemText(22, _translate("Form", "22"))
        self.hours.setItemText(23, _translate("Form", "23"))
        self.minutes.setItemText(0, _translate("Form", "0"))
        self.minutes.setItemText(1, _translate("Form", "1"))
        self.minutes.setItemText(2, _translate("Form", "2"))
        self.minutes.setItemText(3, _translate("Form", "3"))
        self.minutes.setItemText(4, _translate("Form", "4"))
        self.minutes.setItemText(5, _translate("Form", "5"))
        self.minutes.setItemText(6, _translate("Form", "6"))
        self.minutes.setItemText(7, _translate("Form", "7"))
        self.minutes.setItemText(8, _translate("Form", "8"))
        self.minutes.setItemText(9, _translate("Form", "9"))
        self.minutes.setItemText(10, _translate("Form", "10"))
        self.minutes.setItemText(11, _translate("Form", "11"))
        self.minutes.setItemText(12, _translate("Form", "12"))
        self.minutes.setItemText(13, _translate("Form", "13"))
        self.minutes.setItemText(14, _translate("Form", "15"))
        self.minutes.setItemText(15, _translate("Form", "16"))
        self.minutes.setItemText(16, _translate("Form", "17"))
        self.minutes.setItemText(17, _translate("Form", "18"))
        self.minutes.setItemText(18, _translate("Form", "19"))
        self.minutes.setItemText(19, _translate("Form", "20"))
        self.minutes.setItemText(20, _translate("Form", "21"))
        self.minutes.setItemText(21, _translate("Form", "22"))
        self.minutes.setItemText(22, _translate("Form", "23"))
        self.minutes.setItemText(23, _translate("Form", "24"))
        self.minutes.setItemText(24, _translate("Form", "25"))
        self.minutes.setItemText(25, _translate("Form", "26"))
        self.minutes.setItemText(26, _translate("Form", "27"))
        self.minutes.setItemText(27, _translate("Form", "28"))
        self.minutes.setItemText(28, _translate("Form", "29"))
        self.minutes.setItemText(29, _translate("Form", "30"))
        self.minutes.setItemText(30, _translate("Form", "31"))
        self.minutes.setItemText(31, _translate("Form", "32"))
        self.minutes.setItemText(32, _translate("Form", "33"))
        self.minutes.setItemText(33, _translate("Form", "34"))
        self.minutes.setItemText(34, _translate("Form", "35"))
        self.minutes.setItemText(35, _translate("Form", "36"))
        self.minutes.setItemText(36, _translate("Form", "37"))
        self.minutes.setItemText(37, _translate("Form", "38"))
        self.minutes.setItemText(38, _translate("Form", "39"))
        self.minutes.setItemText(39, _translate("Form", "40"))
        self.minutes.setItemText(40, _translate("Form", "41"))
        self.minutes.setItemText(41, _translate("Form", "42"))
        self.minutes.setItemText(42, _translate("Form", "43"))
        self.minutes.setItemText(43, _translate("Form", "44"))
        self.minutes.setItemText(44, _translate("Form", "45"))
        self.minutes.setItemText(45, _translate("Form", "46"))
        self.minutes.setItemText(46, _translate("Form", "47"))
        self.minutes.setItemText(47, _translate("Form", "48"))
        self.minutes.setItemText(48, _translate("Form", "49"))
        self.minutes.setItemText(49, _translate("Form", "50"))
        self.minutes.setItemText(50, _translate("Form", "51"))
        self.minutes.setItemText(51, _translate("Form", "52"))
        self.minutes.setItemText(52, _translate("Form", "53"))
        self.minutes.setItemText(53, _translate("Form", "54"))
        self.minutes.setItemText(54, _translate("Form", "55"))
        self.minutes.setItemText(55, _translate("Form", "56"))
        self.minutes.setItemText(56, _translate("Form", "57"))
        self.minutes.setItemText(57, _translate("Form", "58"))
        self.minutes.setItemText(58, _translate("Form", "59"))
        self.label_2.setText(_translate("Form", "Минуты:"))
        self.pushButton.setText(_translate("Form", "Добавить"))
