# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plan1.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 300)
        Form.setStyleSheet("*{\n"
"    font-size: 12pt;\n"
"    font-family: sans-serif;\n"
"    background-color: #2a323b;\n"
"    color: #ff9900;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #20252b;\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 270, 281, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stopwatch = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopwatch.setObjectName("stopwatch")
        self.horizontalLayout.addWidget(self.stopwatch)
        self.timer_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.timer_btn.setObjectName("timer_btn")
        self.horizontalLayout.addWidget(self.timer_btn)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 271, 21))
        self.label_4.setObjectName("label_4")
        self.start_btn = QtWidgets.QPushButton(Form)
        self.start_btn.setGeometry(QtCore.QRect(10, 90, 141, 21))
        self.start_btn.setObjectName("start_btn")
        self.reset_btn = QtWidgets.QPushButton(Form)
        self.reset_btn.setGeometry(QtCore.QRect(160, 90, 131, 21))
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 240, 281, 22))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.time = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.time.setObjectName("time")
        self.horizontalLayout_3.addWidget(self.time)
        self.alarm = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.alarm.setObjectName("alarm")
        self.horizontalLayout_3.addWidget(self.alarm)
        self.choose_melody = QtWidgets.QPushButton(Form)
        self.choose_melody.setGeometry(QtCore.QRect(10, 120, 281, 21))
        self.choose_melody.setObjectName("choose_melody")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 160, 281, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.minutes_btn = QtWidgets.QComboBox(Form)
        self.minutes_btn.setGeometry(QtCore.QRect(110, 50, 43, 19))
        self.minutes_btn.setObjectName("minutes_btn")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.minutes_btn.addItem("")
        self.seconds_btn = QtWidgets.QComboBox(Form)
        self.seconds_btn.setGeometry(QtCore.QRect(210, 50, 41, 19))
        self.seconds_btn.setObjectName("seconds_btn")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.seconds_btn.addItem("")
        self.hours_btn = QtWidgets.QComboBox(Form)
        self.hours_btn.setGeometry(QtCore.QRect(10, 50, 41, 19))
        self.hours_btn.setObjectName("hours_btn")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.hours_btn.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 48, 31, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 50, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(260, 48, 21, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.stopwatch.setText(_translate("Form", "Секундомер"))
        self.timer_btn.setText(_translate("Form", "Таймер"))
        self.label_4.setText(_translate("Form", "                        Таймер"))
        self.start_btn.setText(_translate("Form", "Старт"))
        self.reset_btn.setText(_translate("Form", "Отмена"))
        self.time.setText(_translate("Form", "Время"))
        self.alarm.setText(_translate("Form", "Будильник"))
        self.choose_melody.setText(_translate("Form", "Выбрать мелодию"))
        self.minutes_btn.setItemText(0, _translate("Form", "0"))
        self.minutes_btn.setItemText(1, _translate("Form", "1"))
        self.minutes_btn.setItemText(2, _translate("Form", "2"))
        self.minutes_btn.setItemText(3, _translate("Form", "3"))
        self.minutes_btn.setItemText(4, _translate("Form", "4"))
        self.minutes_btn.setItemText(5, _translate("Form", "5"))
        self.minutes_btn.setItemText(6, _translate("Form", "6"))
        self.minutes_btn.setItemText(7, _translate("Form", "7"))
        self.minutes_btn.setItemText(8, _translate("Form", "8"))
        self.minutes_btn.setItemText(9, _translate("Form", "9"))
        self.minutes_btn.setItemText(10, _translate("Form", "10"))
        self.minutes_btn.setItemText(11, _translate("Form", "11"))
        self.minutes_btn.setItemText(12, _translate("Form", "12"))
        self.minutes_btn.setItemText(13, _translate("Form", "13"))
        self.minutes_btn.setItemText(14, _translate("Form", "15"))
        self.minutes_btn.setItemText(15, _translate("Form", "16"))
        self.minutes_btn.setItemText(16, _translate("Form", "17"))
        self.minutes_btn.setItemText(17, _translate("Form", "18"))
        self.minutes_btn.setItemText(18, _translate("Form", "19"))
        self.minutes_btn.setItemText(19, _translate("Form", "20"))
        self.minutes_btn.setItemText(20, _translate("Form", "21"))
        self.minutes_btn.setItemText(21, _translate("Form", "22"))
        self.minutes_btn.setItemText(22, _translate("Form", "23"))
        self.minutes_btn.setItemText(23, _translate("Form", "24"))
        self.minutes_btn.setItemText(24, _translate("Form", "25"))
        self.minutes_btn.setItemText(25, _translate("Form", "26"))
        self.minutes_btn.setItemText(26, _translate("Form", "27"))
        self.minutes_btn.setItemText(27, _translate("Form", "28"))
        self.minutes_btn.setItemText(28, _translate("Form", "29"))
        self.minutes_btn.setItemText(29, _translate("Form", "30"))
        self.minutes_btn.setItemText(30, _translate("Form", "31"))
        self.minutes_btn.setItemText(31, _translate("Form", "32"))
        self.minutes_btn.setItemText(32, _translate("Form", "33"))
        self.minutes_btn.setItemText(33, _translate("Form", "34"))
        self.minutes_btn.setItemText(34, _translate("Form", "35"))
        self.minutes_btn.setItemText(35, _translate("Form", "36"))
        self.minutes_btn.setItemText(36, _translate("Form", "37"))
        self.minutes_btn.setItemText(37, _translate("Form", "38"))
        self.minutes_btn.setItemText(38, _translate("Form", "39"))
        self.minutes_btn.setItemText(39, _translate("Form", "40"))
        self.minutes_btn.setItemText(40, _translate("Form", "41"))
        self.minutes_btn.setItemText(41, _translate("Form", "42"))
        self.minutes_btn.setItemText(42, _translate("Form", "43"))
        self.minutes_btn.setItemText(43, _translate("Form", "44"))
        self.minutes_btn.setItemText(44, _translate("Form", "45"))
        self.minutes_btn.setItemText(45, _translate("Form", "46"))
        self.minutes_btn.setItemText(46, _translate("Form", "47"))
        self.minutes_btn.setItemText(47, _translate("Form", "48"))
        self.minutes_btn.setItemText(48, _translate("Form", "49"))
        self.minutes_btn.setItemText(49, _translate("Form", "50"))
        self.minutes_btn.setItemText(50, _translate("Form", "51"))
        self.minutes_btn.setItemText(51, _translate("Form", "52"))
        self.minutes_btn.setItemText(52, _translate("Form", "53"))
        self.minutes_btn.setItemText(53, _translate("Form", "54"))
        self.minutes_btn.setItemText(54, _translate("Form", "55"))
        self.minutes_btn.setItemText(55, _translate("Form", "56"))
        self.minutes_btn.setItemText(56, _translate("Form", "57"))
        self.minutes_btn.setItemText(57, _translate("Form", "58"))
        self.minutes_btn.setItemText(58, _translate("Form", "59"))
        self.seconds_btn.setItemText(0, _translate("Form", "0"))
        self.seconds_btn.setItemText(1, _translate("Form", "1"))
        self.seconds_btn.setItemText(2, _translate("Form", "2"))
        self.seconds_btn.setItemText(3, _translate("Form", "3"))
        self.seconds_btn.setItemText(4, _translate("Form", "4"))
        self.seconds_btn.setItemText(5, _translate("Form", "5"))
        self.seconds_btn.setItemText(6, _translate("Form", "6"))
        self.seconds_btn.setItemText(7, _translate("Form", "7"))
        self.seconds_btn.setItemText(8, _translate("Form", "8"))
        self.seconds_btn.setItemText(9, _translate("Form", "9"))
        self.seconds_btn.setItemText(10, _translate("Form", "10"))
        self.seconds_btn.setItemText(11, _translate("Form", "11"))
        self.seconds_btn.setItemText(12, _translate("Form", "12"))
        self.seconds_btn.setItemText(13, _translate("Form", "13"))
        self.seconds_btn.setItemText(14, _translate("Form", "14"))
        self.seconds_btn.setItemText(15, _translate("Form", "15"))
        self.seconds_btn.setItemText(16, _translate("Form", "16"))
        self.seconds_btn.setItemText(17, _translate("Form", "17"))
        self.seconds_btn.setItemText(18, _translate("Form", "18"))
        self.seconds_btn.setItemText(19, _translate("Form", "19"))
        self.seconds_btn.setItemText(20, _translate("Form", "20"))
        self.seconds_btn.setItemText(21, _translate("Form", "21"))
        self.seconds_btn.setItemText(22, _translate("Form", "22"))
        self.seconds_btn.setItemText(23, _translate("Form", "23"))
        self.seconds_btn.setItemText(24, _translate("Form", "24"))
        self.seconds_btn.setItemText(25, _translate("Form", "25"))
        self.seconds_btn.setItemText(26, _translate("Form", "26"))
        self.seconds_btn.setItemText(27, _translate("Form", "27"))
        self.seconds_btn.setItemText(28, _translate("Form", "28"))
        self.seconds_btn.setItemText(29, _translate("Form", "29"))
        self.seconds_btn.setItemText(30, _translate("Form", "30"))
        self.seconds_btn.setItemText(31, _translate("Form", "31"))
        self.seconds_btn.setItemText(32, _translate("Form", "33"))
        self.seconds_btn.setItemText(33, _translate("Form", "34"))
        self.seconds_btn.setItemText(34, _translate("Form", "35"))
        self.seconds_btn.setItemText(35, _translate("Form", "36"))
        self.seconds_btn.setItemText(36, _translate("Form", "37"))
        self.seconds_btn.setItemText(37, _translate("Form", "38"))
        self.seconds_btn.setItemText(38, _translate("Form", "39"))
        self.seconds_btn.setItemText(39, _translate("Form", "40"))
        self.seconds_btn.setItemText(40, _translate("Form", "41"))
        self.seconds_btn.setItemText(41, _translate("Form", "42"))
        self.seconds_btn.setItemText(42, _translate("Form", "43"))
        self.seconds_btn.setItemText(43, _translate("Form", "44"))
        self.seconds_btn.setItemText(44, _translate("Form", "45"))
        self.seconds_btn.setItemText(45, _translate("Form", "46"))
        self.seconds_btn.setItemText(46, _translate("Form", "47"))
        self.seconds_btn.setItemText(47, _translate("Form", "48"))
        self.seconds_btn.setItemText(48, _translate("Form", "50"))
        self.seconds_btn.setItemText(49, _translate("Form", "51"))
        self.seconds_btn.setItemText(50, _translate("Form", "52"))
        self.seconds_btn.setItemText(51, _translate("Form", "53"))
        self.seconds_btn.setItemText(52, _translate("Form", "54"))
        self.seconds_btn.setItemText(53, _translate("Form", "55"))
        self.seconds_btn.setItemText(54, _translate("Form", "56"))
        self.seconds_btn.setItemText(55, _translate("Form", "57"))
        self.seconds_btn.setItemText(56, _translate("Form", "58"))
        self.seconds_btn.setItemText(57, _translate("Form", "59"))
        self.hours_btn.setItemText(0, _translate("Form", "0"))
        self.hours_btn.setItemText(1, _translate("Form", "1"))
        self.hours_btn.setItemText(2, _translate("Form", "2"))
        self.hours_btn.setItemText(3, _translate("Form", "3"))
        self.hours_btn.setItemText(4, _translate("Form", "4"))
        self.hours_btn.setItemText(5, _translate("Form", "5"))
        self.hours_btn.setItemText(6, _translate("Form", "6"))
        self.hours_btn.setItemText(7, _translate("Form", "7"))
        self.hours_btn.setItemText(8, _translate("Form", "8"))
        self.hours_btn.setItemText(9, _translate("Form", "9"))
        self.hours_btn.setItemText(10, _translate("Form", "10"))
        self.hours_btn.setItemText(11, _translate("Form", "11"))
        self.hours_btn.setItemText(12, _translate("Form", "12"))
        self.hours_btn.setItemText(13, _translate("Form", "13"))
        self.hours_btn.setItemText(14, _translate("Form", "14"))
        self.hours_btn.setItemText(15, _translate("Form", "15"))
        self.hours_btn.setItemText(16, _translate("Form", "16"))
        self.hours_btn.setItemText(17, _translate("Form", "17"))
        self.hours_btn.setItemText(18, _translate("Form", "18"))
        self.hours_btn.setItemText(19, _translate("Form", "19"))
        self.hours_btn.setItemText(20, _translate("Form", "20"))
        self.hours_btn.setItemText(21, _translate("Form", "21"))
        self.hours_btn.setItemText(22, _translate("Form", "22"))
        self.hours_btn.setItemText(23, _translate("Form", "23"))
        self.label.setText(_translate("Form", "ч"))
        self.label_2.setText(_translate("Form", "мин"))
        self.label_3.setText(_translate("Form", "с"))
